defaults: &defaults

development:
  <<: *defaults
  facebook_app_id: "922539601172541"
  facebook_secret: "f3b1858a69c7419da98324b4fd078096"

test:
  <<: *defaults

production:
  <<: *defaults
  facebook_app_id: "784389335013233"
  facebook_secret: "d7ba8c239b96acce604f07a9c2570cff"